<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Kacode-MBP" ignored="1" name="Default test(failed)(failed)" tests="2" failures="1" timestamp="12 Jul 2022 09:33:56 GMT" time="0.044" errors="0">
  <testcase name="test2" time="0.011" classname="demo.TestNGRetryFailedDemo"/>
  <testcase name="test3" time="0.007" classname="demo.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:20)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
